In [1]:
import pandas as pd

In [2]:
df_training_7 = pd.read_csv('ACT7_competition_training.csv', header=0)
df_training_2 = pd.read_csv('ACT2_competition_training.csv', header=0)
df_training_3 = pd.read_csv('ACT3_competition_training.csv', header=0)
df_training_4 = pd.read_csv('ACT4_competition_training.csv', header=0)
df_training_5 = pd.read_csv('ACT5_competition_training.csv', header=0)
df_training_6 = pd.read_csv('ACT6_competition_training.csv', header=0)
df_training_7 = pd.read_csv('ACT7_competition_training.csv', header=0)
df_training_8 = pd.read_csv('ACT8_competition_training.csv', header=0)
df_training_9 = pd.read_csv('ACT9_competition_training.csv', header=0)
df_training_10 = pd.read_csv('ACT10_competition_training.csv', header=0)
df_training_11 = pd.read_csv('ACT11_competition_training.csv', header=0)
df_training_12 = pd.read_csv('ACT12_competition_training.csv', header=0)
df_training_13 = pd.read_csv('ACT13_competition_training.csv', header=0)
df_training_14 = pd.read_csv('ACT14_competition_training.csv', header=0)
df_training_15 = pd.read_csv('ACT15_competition_training.csv', header=0)

In [15]:
df_training_7['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_7['MOLECULE']))
df_training_1['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_1['MOLECULE']))
df_training_2['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_2['MOLECULE']))
df_training_3['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_3['MOLECULE']))
df_training_4['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_4['MOLECULE']))
df_training_5['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_5['MOLECULE']))
df_training_6['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_6['MOLECULE']))
df_training_8['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_8['MOLECULE']))
df_training_9['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_9['MOLECULE']))
df_training_10['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_10['MOLECULE']))
df_training_11'MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_11['MOLECULE']))
df_training_12['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_12['MOLECULE']))
df_training_13['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_13['MOLECULE']))
df_training_14['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_14['MOLECULE']))
df_training_15['MOLECULE_ID'] = list(map(lambda x : str(x).split('_')[2], df_training_15['MOLECULE']))

,MOLECULE,Act,D_37,D_38,D_39,D_40,D_42,D_43,D_44,D_45,...,D_10740,D_10741,D_10742,D_10744,D_10745,D_10746,D_10747,D_10764,D_10770,MOLECULE_ID
0,ACT7_M_5058,70.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5058
1,ACT7_M_6406,74.68,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6406
2,ACT7_M_12634,2.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12634
3,ACT7_M_17594,0.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,17594
4,ACT7_M_17627,73.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,17627

In [17]:
df_training_1["Number_Nonzero_Descriptor"] =  = df_training_1.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_1[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_2["Number_Nonzero_Descriptor"] =  = df_training_2.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_2[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_3["Number_Nonzero_Descriptor"] =  = df_training_3.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_3[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_4["Number_Nonzero_Descriptor"] =  = df_training_4.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_4[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_5["Number_Nonzero_Descriptor"] =  = df_training_5.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_5[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_6["Number_Nonzero_Descriptor"] =  = df_training_6.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_6[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_1["Number_Nonzero_Descriptor"] =  = df_training_1.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_7[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_7["Number_Nonzero_Descriptor"] =  = df_training_7.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_8[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_8["Number_Nonzero_Descriptor"] =  = df_training_8.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_9[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_9["Number_Nonzero_Descriptor"] =  = df_training_9.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_10[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_1["Number_Nonzero_Descriptor"] =  = df_training_10.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_10[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_11["Number_Nonzero_Descriptor"] =  = df_training_11.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_11[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_12["Number_Nonzero_Descriptor"] =  = df_training_12.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_12[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_13["Number_Nonzero_Descriptor"] =  = df_training_13.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_13[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_14["Number_Nonzero_Descriptor"] =  = df_training_14.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_14[['Act', 'Number_Nonzero_Descriptor']].corr())
df_training_15["Number_Nonzero_Descriptor"] =  = df_training_15.iloc[:,2:-2].apply(lambda x: len(x[x != 0]), axis = 1)
print(df_training_15[['Act', 'Number_Nonzero_Descriptor']].corr())

In [22]:
# In activity 7, Check if there is correlation 
# between the number of non-zero descriptors and activity level measurement

# df_training_7[['Act', 'Number_Nonzero_Descriptor']].cov()

                                Act  Number_Nonzero_Descriptor
Act                        1.000000                   0.164112
Number_Nonzero_Descriptor  0.164112                   1.000000

In [42]:
#apply(lambda x: len(x[x !=0]), axis =0)
# important_descriptors_cross_molecules = df_training_7.iloc[:, 2:-3]
# counts_for_nonzero_descriptors = important_descriptors_cross_molecules.apply(lambda x: len(important_descriptors_cross_molecules[x != 0]))
# counts_for_nonzero_descriptors.idmax()